# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/sm8350-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter RMX3360 RMX3363,$(TARGET_DEVICE)),)

endif
